#!/usr/bin/env python3
"""Build Gerrit ReviewInput JSON from reply drafts."""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from typing import Any


DEFAULT_TAG = "autogenerated:codex-gerrit-review"
CODEX_PREFIX = "[Codex로 생성됨]"


def ensure_codex_prefix(message: str) -> str:
    stripped = message.lstrip()
    if stripped.startswith(CODEX_PREFIX):
        return message
    return f"{CODEX_PREFIX} {message}"


def load_json(path: str | None) -> Any:
    if path:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    return json.load(sys.stdin)


def iter_replies(data: Any) -> list[dict[str, Any]]:
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        for key in ("replies", "comments", "drafts"):
            value = data.get(key)
            if isinstance(value, list):
                return value
    raise ValueError("Input must be a list or an object with replies/comments/drafts list")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", nargs="?", help="JSON file containing reply drafts; defaults to stdin")
    parser.add_argument("--message", default="", help="Change-level review message")
    parser.add_argument("--notify", default="NONE", choices=["NONE", "OWNER", "OWNER_REVIEWERS", "ALL"])
    parser.add_argument("--tag", default=DEFAULT_TAG)
    parser.add_argument("--include-verdict-prefix", action="store_true")
    args = parser.parse_args()

    data = load_json(args.input)
    comments: dict[str, list[dict[str, Any]]] = defaultdict(list)
    skipped: list[dict[str, Any]] = []

    for reply in iter_replies(data):
        path = reply.get("file") or reply.get("path")
        line = reply.get("line")
        message = reply.get("reply") or reply.get("draft") or reply.get("message")
        if not path or not message:
            skipped.append(reply)
            continue
        if args.include_verdict_prefix and reply.get("verdict"):
            message = f"[{reply['verdict']}] {message}"
        message = ensure_codex_prefix(message)
        item: dict[str, Any] = {
            "message": message,
            "unresolved": bool(reply.get("unresolved", False)),
        }
        if line is not None:
            item["line"] = int(line)
        if reply.get("in_reply_to"):
            item["in_reply_to"] = reply["in_reply_to"]
        comments[path].append(item)

    review_input: dict[str, Any] = {
        "tag": args.tag,
        "notify": args.notify,
        "omit_duplicate_comments": True,
        "comments": comments,
    }
    if args.message:
        review_input["message"] = ensure_codex_prefix(args.message)

    result = {
        "reviewInput": review_input,
        "summary": {
            "commentCount": sum(len(values) for values in comments.values()),
            "fileCount": len(comments),
            "notify": args.notify,
            "tag": args.tag,
            "skippedCount": len(skipped),
        },
        "skipped": skipped,
    }
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
