#!/usr/bin/env python3
"""Dry-run or publish existing Gerrit draft comments with a confirmation guard."""

from __future__ import annotations

import argparse
import base64
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


XSSI_PREFIX = ")]}'"
DEFAULT_TAG = "autogenerated:codex-gerrit-review"
SKILL_DIR = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG_PATH = SKILL_DIR / "config" / "account.json"
DEFAULT_CONFIG_LABEL = "config/account.json"


class MissingAccountConfig(Exception):
    pass


def redact_url(url: str) -> str:
    return "<redacted-base-url>" if url else ""


def redact_error(error: BaseException, base: str) -> str:
    return str(error).replace(base, redact_url(base)) if base else str(error)


def display_config_path(path: Path) -> str:
    if path.resolve() == DEFAULT_CONFIG_PATH.resolve():
        return DEFAULT_CONFIG_LABEL
    return str(path)


def account_config_guidance(path: Path) -> dict[str, Any]:
    return {
        "configured": False,
        "config_path": display_config_path(path),
        "message": "Gerrit account config is required before using gerrit-review.",
        "next_step": "scripts/configure_account.py",
    }


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise MissingAccountConfig(json.dumps(account_config_guidance(path), indent=2))
    with path.open("r", encoding="utf-8") as handle:
        config = json.load(handle)
    account = config.get("account") or {}
    missing = [f"account.{key}" for key in ("user", "base_url") if not account.get(key)]
    if missing:
        guidance = account_config_guidance(path)
        guidance["missing"] = missing
        raise MissingAccountConfig(json.dumps(guidance, indent=2))
    return config


def build_headers(config: dict[str, Any]) -> dict[str, str]:
    headers: dict[str, str] = {}
    account = config.get("account") or {}
    auth_header = account.get("auth_header")
    account_user = account.get("user")
    password = account.get("password")
    if auth_header:
        key, _, value = auth_header.partition(":")
        if not key or not value:
            raise ValueError("account.auth_header must be formatted as 'Header-Name: value'")
        headers[key.strip()] = value.strip()
    elif password:
        if not account_user:
            raise ValueError("account.password is set, but account.user is missing")
        token = base64.b64encode(f"{account_user}:{password}".encode("utf-8")).decode("ascii")
        headers["Authorization"] = f"Basic {token}"
    return headers


def parse_response(text: str) -> Any:
    if text.startswith(XSSI_PREFIX):
        text = text.split("\n", 1)[1] if "\n" in text else ""
    return json.loads(text) if text.strip() else {}


def request_json(url: str, headers: dict[str, str], method: str = "GET", body: dict[str, Any] | None = None) -> Any:
    data = json.dumps(body).encode("utf-8") if body is not None else None
    request = urllib.request.Request(url, data=data, method=method)
    request.add_header("Content-Type", "application/json; charset=utf-8")
    for key, value in headers.items():
        request.add_header(key, value)
    with urllib.request.urlopen(request, timeout=30) as response:
        return parse_response(response.read().decode("utf-8"))


def flatten_drafts(data: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    drafts: list[dict[str, Any]] = []
    for path, comments in data.items():
        for comment in comments:
            drafts.append(
                {
                    "id": comment.get("id"),
                    "path": path,
                    "line": comment.get("line"),
                    "unresolved": comment.get("unresolved"),
                }
            )
    return drafts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=str(DEFAULT_CONFIG_PATH), help=f"Skill-local account config path. Defaults to {DEFAULT_CONFIG_LABEL}")
    parser.add_argument("--change", required=True, help="Gerrit change number or URL-encoded change id")
    parser.add_argument("--revision", required=True, help="Patch set number, revision id, or commit SHA")
    parser.add_argument("--notify", default="NONE", choices=["NONE", "OWNER", "OWNER_REVIEWERS", "ALL"])
    parser.add_argument("--tag", default=DEFAULT_TAG)
    parser.add_argument("--execute", action="store_true", help="Publish drafts. Without this, only print dry-run JSON.")
    parser.add_argument("--confirm", help="Required exact value for execution: PUBLISH_DRAFTS:<change>,<revision>")
    args = parser.parse_args()

    required_confirm = f"PUBLISH_DRAFTS:{args.change},{args.revision}"
    if args.execute and args.confirm != required_confirm:
        print(
            json.dumps(
                {
                    "dryRun": False,
                    "summary": {
                        "change": args.change,
                        "revision": args.revision,
                        "requiredConfirm": required_confirm,
                    },
                    "error": "confirmation mismatch",
                },
                indent=2,
                ensure_ascii=False,
            ),
            file=sys.stderr,
        )
        return 2

    config_path = Path(args.config).expanduser()
    try:
        config = load_config(config_path)
    except MissingAccountConfig as error:
        print(str(error), file=sys.stderr)
        return 2
    headers = build_headers(config)
    if not headers:
        print("REST authentication is required in config/account.json", file=sys.stderr)
        return 2

    base = ((config.get("account") or {}).get("base_url") or "").rstrip("/")
    drafts_url = f"{base}/a/changes/{args.change}/revisions/{args.revision}/drafts/"
    review_url = f"{base}/a/changes/{args.change}/revisions/{args.revision}/review"
    display_review_url = f"{redact_url(base)}/a/changes/{args.change}/revisions/{args.revision}/review"
    try:
        draft_data = request_json(drafts_url, headers)
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace").replace(base, redact_url(base))
        result = {
            "dryRun": not args.execute,
            "summary": {
                "change": args.change,
                "revision": args.revision,
                "notify": args.notify,
                "tag": args.tag,
                "requiredConfirm": required_confirm,
            },
            "error": f"failed to fetch drafts: HTTP {error.code}: {detail}",
        }
        print(json.dumps(result, indent=2, ensure_ascii=False), file=sys.stderr)
        return 1
    except Exception as error:
        result = {
            "dryRun": not args.execute,
            "summary": {
                "change": args.change,
                "revision": args.revision,
                "notify": args.notify,
                "tag": args.tag,
                "requiredConfirm": required_confirm,
            },
            "error": f"failed to fetch drafts: {redact_error(error, base)}",
        }
        print(json.dumps(result, indent=2, ensure_ascii=False), file=sys.stderr)
        return 1
    drafts = flatten_drafts(draft_data)
    body = {"drafts": "PUBLISH", "notify": args.notify, "tag": args.tag}

    result: dict[str, Any] = {
        "dryRun": not args.execute,
        "summary": {
            "change": args.change,
            "revision": args.revision,
            "draftCount": len(drafts),
            "notify": args.notify,
            "tag": args.tag,
            "requiredConfirm": required_confirm,
        },
        "request": {"method": "POST", "url": display_review_url, "body": body},
        "drafts": drafts,
    }

    if args.execute:
        if not drafts:
            result["error"] = "no drafts to publish"
            print(json.dumps(result, indent=2, ensure_ascii=False), file=sys.stderr)
            return 2
        try:
            result["response"] = request_json(review_url, headers, method="POST", body=body)
        except urllib.error.HTTPError as error:
            result["httpStatus"] = error.code
            result["error"] = error.read().decode("utf-8", errors="replace").replace(base, redact_url(base))
            print(json.dumps(result, indent=2, ensure_ascii=False), file=sys.stderr)
            return 1
        except Exception as error:
            result["error"] = f"failed to publish drafts: {redact_error(error, base)}"
            print(json.dumps(result, indent=2, ensure_ascii=False), file=sys.stderr)
            return 1

    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
